resource "local_file" "whale" {
  filename   = "/root/whale"
  content    = "whale"
  depends_on = [local_file.krill]
}

resource "local_file" "krill" {
  filename = "/root/krill"
  content  = "krill"
}

 cat main.tf
resource "random_uuid" "id1" {

}
resource "random_uuid" "id2" {

}
resource "random_uuid" "id3" {

}
resource "random_uuid" "id4" {

}
resource "random_uuid" "id5" {

}
resource "random_uuid" "id6" {

}
resource "random_uuid" "id7" {

}
resource "random_integer" "order1" {
  min     = 1
  max     = 99999

}
resource "random_integer" "order2" {
  min     = 1
  max     = 222222

}


#####################################################


#### cat output.tf
output "id1" {
   value = random_uuid.id1.result
}
output "id2" {
    value = random_uuid.id2.result

}
output "id3" {
    value = random_uuid.id3.result

}

output "id4" {
    value = random_uuid.id4.result

}
output "id5" {
    value = random_uuid.id5.result
}

output "id6" {
    value = random_uuid.id6.result

}
output "id7" {
    value = random_uuid.id7.result

}
output "order1" {
 value = random_integer.order1.result

}
output "order2" {
 value = random_integer.order1.result

}
root in ~/terraform-projects/data via 💠 default on ☁️  (us-east-1)
❯


resource "random_pet" "my-pet" {

  length    = var.length
}

output "pet-name" {

        value = random_pet.my-pet.id
        description = "Record the value of pet ID generated by the random_pet resource"
}

resource "local_file" "welcome" {
    filename = "/root/message.txt"
    content = "Welcome to Kodekloud."
}

output "welcome_message" {
  value = local_file.welcome.content
}
